export type Job = {
  id: string;
  title: string;
  location: string;
  type: string;
  seniority?: string;
  summary: string;
  responsibilities: string[];
  requirements: string[];
  apply: string; 
  salary: string;
  deadline: string;
}

export const jobs: Job[] = [
  {
    id: "Graduate Surveryor",
    title: "Graduate Surveryor",
    location: "somolu, Lagos",
    type: "Full-time",
    seniority: "junior",
    summary:
      "Sanni, Ojo& Partners is looking for adiligent and motivated Graduate Surveyorto join our Survey Unit . The ideal candidate will lead the design and supervision of civil and structural engineering projects, ensuring compliance with safety, quality, and industry standards, while mentoring younger engineers and contributing to innovative, sustainable solutions.",
    responsibilities: [
      "Assist with leveling, traversing & topographical surveys",
"Operate Total Station, Levels & GNSS equipment (under supervision)",
"Process & reduce field data accurately",
"Prepare survey drawings using AutoCAD/Civil 3D",
"Maintain survey logs, records & documentation",
"Structured training on GIS, photogrammetry & survey software",
    ],
    requirements: [
      "B.Sc / B.Techin Surveying, Geomatics, Geoinformatics, Geodetic/Mapping Sciences.",
"NYSC completed.",
"0–2 years experience (IT experience is an advantage).",
"Basic knowledge of survey instruments and techniques.",
"Introductory competence in AutoCAD / Civil 3D.",
"Good computer skills (MS Office).",
"Strong attention to detail, accuracy & willingness to learn",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:hr@sop-consulting.com ">hr@sop-consulting.com </a> using “Application –Graduate Surveyor” as  the subject of the mail.',
    salary: "Not specific",
    deadline: "9th May, 2026",
  },
{
    id: "Maintenance Personnel",
    title: "Maintenance Personnel",
    location: "Berger, Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "Ensure Hotel Capitol's facilities, equipment, and systems are in optimal condition, providing a comfortable and safe environment for guests",
    responsibilities: [
      "Plumbing Maintenance: Fix leaks, unclog drains, maintain water systems, and ensure efficient water usage.",
"Electrical Maintenance: Handle lighting, power outlets, generators, and electrical equipment repairs.",
"AC & HVAC: Service air conditioning units, ensure temperature control, and perform routine checks.",
"General Repairs: Fix furniture, doors, and locks, and respond to guest requests promptly.",
"Safety & Compliance: Ensure fire safety systems are functional, conduct inspections, and report issues to management.",
"Collaboration: Work with other departments for smooth operations and report maintenance status",
    ],
    requirements: [
      "Trade certificate or Diploma in Electrical, Plumbing, HVAC, or related field.",
"Minimum of 2 years of experience in hotel or commercial building maintenance.",
"Skills in troubleshooting, basic repairs, and safety protocols.",
"Ability to work flexible hours, including weekends.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:hr@russelsmithgroup.com">hr@russelsmithgroup.com</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "24th March, 2026",
  },
{
    id: "Structural Design Engineer ",
    title: "Structural Design Engineer ",
    location: "Ikoyi, Lagos",
    type: "Full-time",
    seniority: "junior",
    summary:
      "The ideal candidate will have a strong understanding of structural engineering principles, construction methods, and project management. You will collaborate with architects, contractors, and other engineering disciplines to ensure accurate and efficient implementation of structural designs on-site",
    responsibilities: [
      "Review and interpret structural design plans to ensure compliance with building codes and project requirements.",
"Collaborate with project managers, architects, and construction teams to develop methodologies and schedules.",
"Conduct site visits to monitor progress and ensure adherence to design specifications and quality standards.",
"Provide technical guidance and support to the construction teams, addressing any issues during construction.",
"Perform structural calculations and analyses to validate the safety and integrity of designs.",
"Prepare and review construction documents, including shop drawings and change orders.",
"Evaluate materials and techniques to ensure cost-effectiveness and sustainability.",
"Inspect existing structures and recommend repairs or reinforcements as necessary.",
"Maintain accurate records, including reports on site conditions and compliance with safety regulations.",
"Stay updated on industry trends, technologies, and regulatory changes.",
    ],
    requirements: [
      "5 years of experience in Structural Engineering or a related field.",
"Professional Engineer (PE) license or ability to obtain licensure within a specified timeframe.",
"Expertise in structural engineering within construction, especially in commercial, residential, or infrastructure projects.",
"Proficiency in structural design software (AutoCAD, Revit, SAP2000, ETABS).",
"Strong knowledge of building codes, safety regulations, and construction standards",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:precious@ldd-consulting.com ">precious@ldd-consulting.com </a> using the job title as the subject of the mail.',
    salary: "N800,000 / month.",
    deadline: "Not specific",
  },
{
    id: "AI / ML Data Engineer",
    title: "AI / ML Data Engineer",
    location: "Lagos",
    type: "Full-time(Remote)",
    seniority: "Senior",
    summary:
      "Design, build, and maintain scalable data pipelines to ingest, process, and transform structured and unstructured data from multiple sources.",
    responsibilities: [
      "Optimize data storage, retrieval, and processing performance across large datasets.",
"Prepare, clean, and transform datasets required for training, validating, and testing machine learning models.",
"Collaborate with data scientists and ML engineers to ensure data readiness for model development and experimentation.",
"Support feature engineering processes and maintain feature stores where applicable.",
"Build and manage data infrastructure that supports AI/ML workloads, including batch and real-time processing systems.",
"Implement scalable data architectures using cloud platforms or distributed systems.",
"Ensure high data availability, integrity, and reliability across data environments.",
"Implement data validation, monitoring, and quality control processes.",
"Ensure data governance policies, compliance standards, and security best practices are followed.",
"Manage metadata, data lineage, and documentation for AI/ML datasets.",
"Work closely with data scientists, analysts, and software engineers to operationalize machine learning models.",
"Support deployment of ML models into production environments through robust data infrastructure.",
"Continuously evaluate new tools, technologies, and frameworks to improve data engineering and AI capabilities.",
    ],
    requirements: [
      "Bachelor’s Degree in Computer Science, Data Engineering, Software Engineering, Artificial Intelligence, or a related field.",
"3+ years of experience in data engineering, data platforms, or related technical roles.",
"Experience working with machine learning pipelines or AI-driven data environments.",
"Proven experience building scalable data pipelines and managing large datasets.",
"Strong proficiency in Python, SQL, or Scala.",
"Experience with data pipeline tools such as Apache Airflow, Kafka, or similar frameworks.",
"Familiarity with cloud platforms (AWS, Azure, or Google Cloud) and cloud-based data services.",
"Experience with data warehousing solutions such as Snowflake, BigQuery, or Redshift.",
"Understanding of machine learning workflows and data preparation techniques.",
"Strong analytical and problem-solving skills.",
"Ability to work collaboratively in cross-functional teams.",
"Good documentation and communication skills.",
"Strong attention to data quality, security, and governance practices",
    ],
    apply:
      'Interested and qualified candidates should sclick: <a href="https://appzonegroup.zohorecruit.com/recruit/PortalDetail.na?iframe=true&digest=J2N79DxkoZXbZ7tAxeZfGj0sl6oI6higx9JSCrx5eDY-&jobid=284302000031680136&widgetid=284302000000905137&embedsource=">HERE</a> to apply.',
    salary: "Not specific",
    deadline: "30th April, 2026.",
  },
{
    id: "Graphics Designer",
    title: "Graphics Designer",
    location: "Port Harcourt, Rivers",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "Velox Real Estate and investment Limited is a real estate company, specialised in the sales and development of landed properties and we are located in portharcourt, Rivers state, Nigeria.",
    responsibilities: [
      "Designing diverse marketing assets including brochures, site boards, banners, and engaging social media graphics.",
"Developing property adverts and performing basic video editing or motion graphics for online promotions.",
"Preparing high-quality files for both professional print production and seamless digital publishing.",
    ],
    requirements: [
      "Mastering industry-standard tools such as Adobe Photoshop, Illustrator, and CorelDRAW to deliver polished results.",
    ],
    apply:
      'Interested and qualified candidates should click <a href="http://bit.ly/3OQ1BdZ">HERE</a> to apply online.',
    salary: "Not specific",
    deadline: "23rd March, 2026.",
  },
  {
    id: "Site Engineer",
    title: "Site Engineer",
    location: "Abuja",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "The Site Engineer will be responsible for supervising construction activities on-site, ensuring projects are executed according to approved drawings, timelines, quality standards, and regulatory requirements.",
    responsibilities: [
      "Supervise and coordinate daily construction activities on-site.",
"Ensure construction works are executed according to approved drawings, specifications, and project plans.",
"Monitor project progress and report updates to the Head of Projects/Project Manager.",
"Ensure strict adherence to site safety standards and regulations.",
"Coordinate with contractors, consultants, architects, and other stakeholders.",
"Inspect construction work to ensure quality control and compliance with project specifications.",
"Resolve technical issues that may arise during construction.",
"Maintain proper documentation of site activities, materials, and labour.",
"Ensure compliance with regulatory authorities and building standards.",
    ],
    requirements: [
      "Bachelor’s Degree or HND in Civil Engineering or related engineering discipline.",
"Must be COREN registered (Council for the Regulation of Engineering in Nigeria).",
"3 – 5 years’ experience in construction or real estate development.",
"Strong knowledge of construction processes and site supervision.",
"Ability to read and interpret structural and architectural drawings.",
"Excellent communication and problem-solving skills.",
"Proficiency in Microsoft Office and site reporting tools.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:hr@hrsowreallag@gmail.com ">hrsowreallag@gmail.com </a> using the “Site Engineer – Abuja” as the subject of the mail.',
    salary: "Not specific",
    deadline: "Not specific",
  },
{
    id: "Project Engineer (Civil / Structural)",
    title: "Project Engineer (Civil / Structural)",
    location: "Shomolu, Lagos",
    type: "Full-time",
    seniority: "Junior",
    summary:
      "Sanni, Ojo & Partners Consulting Limited is a multidisciplinary engineering consultancy with over three decades of experience in civil, structural, and project management services.",
    responsibilities: [
      "Perform structural analysis and detailed design of RC and steel elements",
"Coordinate with architects, BIM-CADteams, contractors, and senior engineers",
"Prepare technical reports, calculations, and design documentation",
"Conduct supervised site inspections and ensure quality compliance",
"Build competence in software such asProtaStructure, Robot, Tekla, Civil 3D, AutoCAD, and Revit.",
"Manage engineering tasks for small–medium scale projects",
    ],
    requirements: [
      "BS. c / B.Eng Degree (Minimum 2:1) in Civil/Structural/Geotechnical Engineering",
"2 – 3 years post-NYSC design experience",
"Strong structural analysis background",
"Proficiencyin AutoCAD/Revit and design software",
"Good communication, teamwork, and coordination skills",
"Detail-oriented and able to meet deadlines.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:hr@sop-consulting.com ">hr@sop-consulting.com </a> using the job "Application Engineer” the subject of the mail.',
    salary: "N250,000 - N350,000 per month.",
    deadline: "9th April, 2026",
  },
{
    id: "Cyber Security Officer (NYSC)",
    title: "Cyber Security Officer (NYSC)",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "If you’re passionate about combining technical precision with business strategy, this is your opportunity to make an impact with a team that thrives on innovation and excellence.",
    responsibilities: [
      "Support with technical qualification of sales opportunities",
"Provide answers to (technical) questions in a Request for Information(RFI) or a Request for Proposal (RFP) and Request for Quotation (RFQ).",
"Build custom demonstrations or Proof Of Concepts (POC) when/where necessary.",
"Understand IT infrastructure and cybersecurity architectures.",
"Can design, present, and deliver tailored technology solutions that drive client success.",
"Enjoy collaborating across teams and engaging with enterprise customers.",
"Daily administrative tasks, reporting, and communication with the relevant departments in the organization.",
    ],
    requirements: [
      "Minimum academic qualification of bachelor’s degree in computer science or a technology-related field from a recognized University.",
"0-2 years’ experience in cybersecurity and network security",
"Hands-on experience with security tools, firewalls, and endpoint protection a plus",
"Ability to assess and mitigate common threats and vulnerabilities",
"Relevant certifications a plus (e.g., CompTIA Security+, CEH, CCNA Security)",
"Excellent problem-solving and analytical skills.",
"Good presentation skills.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:recruitment@prolatotech.">recruitment@prolatotech.</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "10th April, 2026.",
  },
{
    id: "Professional Graphics Designer",
    title: "Professional Graphics Designer",
    location: "Enugu",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We are seeking a talented and detail-oriented Professional Graphics Designer to join our creative team. The ideal candidate will bring ideas to life through compelling visuals across digital and print media, ensuring brand consistency and delivering high-quality designs that engage and inspire our audience.",
    responsibilities: [
      "Lead the creation of visual concepts for marketing materials, social media, websites, and other digital and print platforms.",
"Collaborate closely with cross-functional teams to develop design solutions that align with brand identity and project objectives.",
"Design and oversee high-quality graphics, illustrations, and layouts for advertisements, brochures, flyers, banners, and other promotional materials.",
"Ensure consistent application of brand guidelines across all creative outputs and update guidelines when necessary.",
"Review and prepare final design files for print and digital use, ensuring accuracy in formatting, color, and resolution.",
"Provide creative direction and mentorship to junior designers, including reviewing work and offering constructive feedback.",
      "Manage multiple design projects simultaneously while meeting tight deadlines and maintaining quality standards.",
"Interpret and implement feedback from management and stakeholders to refine and improve designs.",
"Support the development of creative concepts for campaigns, client presentations, and internal projects.",
"Stay up to date with industry trends, design tools, and best practices to keep the company’s visual assets fresh and competitive",
    ],
    requirements: [
      "Proven experience as a graphic designer or in a similar design leadership role.",
"Advanced proficiency in design tools such as Adobe Creative Suite (Photoshop, Illustrator, InDesign).",
"Strong understanding of typography, colour theory, layout design, and visual hierarchy.",
"Excellent portfolio demonstrating a wide range of high-quality design projects and creative leadership.",
"Ability to work collaboratively in a fast-paced environment while managing multiple projects and priorities.",
"Strong communication skills, including the ability to present and defend creative ideas.",
"Exceptional attention to detail and a strong commitment to high-quality design output.",
"Excellent time management and organisational skills with a proven ability to meet deadlines.",
"==========",
"Additional skill (advantage):",
"Bachelor’s degree in graphic design or visual arts.",
"Working knowledge of web design principles (HTML/CSS) is an added advantage.",
"Experience with video editing, motion graphics, or animation tools is a plus.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:hrsupport@9figuremedia.com ">hrsupport@9figuremedia.com </a> using “Professional Graphics Designer” as the subject of the mail.',
    salary: "Not specific",
    deadline: "31st March, 2026.",
  },
{
    id: "Junior Network Solutions Engineer (NYSC)",
    title: "Junior Network Solutions Engineer (NYSC)",
    location: "Suruler, Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "Prolato Technologies Limited is an indigenous ICT company with a clear and dedicated focus on ICT ICT Infrastructure, IT Security, support and professional services delivery. We are visionary and a reliable IT partner filling in the gaps in the IT sector. We accomplish this by analyzing each business’s needs, ensuring that every project delivers the right solutions to meet strategic business targets.",
    responsibilities: [
      "Support with technical qualification of sales opportunities",
"Provide answers to (technical) questions in a Request for Information(RFI) or a Request for Proposal (RFP) and Request for Quotation (RFQ)",
"Build custom demonstrations or Proof Of Concepts (POC) when/where necessary.",
"Understand IT infrastructure and network architectures.",
"Can design, present, and deliver tailored technology solutions that drive client success.",
"Enjoy collaborating across teams and engaging with enterprise customers.",
"If you’re passionate about combining technical precision with business strategy, this is your opportunity to make an impact with a team that thrives on innovation and excellence.",
"Daily administrative tasks, reporting, and communication with the relevant departments in the organization.",
    ],
    requirements: [
      "Minimum academic qualification of bachelor’s degree in computer science or a technology-related field from a recognized University.",
"0-2 years’ experience in network engineering",
"Hands-on experience with Cisco network devices such as switches , router a plus",
"Relevant certifications a plus (e.g., CompTIA A+, CCNA )",
"Excellent problem-solving and analytical skills.",
"Good presentation skills.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:recruitment@prolatotech.">recruitment@prolatotech.</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "10th April, 2026",
  },
{
    id: "IT Team Lead",
    title: "IT Team Lead",
    location: "Lekki Phase 1, Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "As the IT Team Lead, you will play a pivotal role in managing and optimizing the company’s technology infrastructure.",
    responsibilities: [
      "Designing, developing, and maintaining backend software applications, APIs, and system integrations.",
"Configuring and maintaining servers, networks, and other core IT infrastructure.",
"Acting as the ERP system expert, ensuring proper implementation, maintenance, and optimization.",
"Supporting setup, installation, maintenance, and troubleshooting of hardware systems (computers, printers, routers, switches, etc.).",
"Monitoring system performance and availability; identifying and resolving technical issues promptly.",
"Managing database design, performance tuning, backups, and security.",
"Implementing and maintaining cybersecurity measures to protect organizational data and assets.",
"Collaborating with internal teams to gather requirements, propose solutions, and deploy reliable software systems.",
"Maintaining accurate technical documentation, system configurations, and support log",
"Providing user support and training on hardware/software usage.",
"Participating in system upgrades, patch management, and continuous improvement efforts.",
"Staying updated with emerging technologies, tools, and industry best practices.",
    ],
    requirements: [
      "Bachelor’s degree in Computer Science, Information Technology, Software Engineering, or a related field.",
"4 - 6 years of relevant IT experience, with at least 1–2 years in a supervisory role.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:growthpartnersintermediaries@gmail.com">growthpartnersintermediaries@gmail.com </a> using "IT Team Lead"  as the subject of the mail.',
    salary: "Not specific",
    deadline: "31st March, 2026.",
  },
{
    id: "HSE Manager",
    title: "HSE Manager",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We are seeking a highly experienced and proactive HSE Manager with over 13 years of core construction experience to lead and manage our Health, Safety, and Environment (HSE) function across multiple construction projects",
    responsibilities: [
      "Lead, manage, and supervise the HSE team across all construction sites",
"Develop, implement, and enforce HSE policies, procedures, and management systems",
"Ensure full compliance with statutory regulations, industry standards, and client HSE requirements",
"Conduct risk assessments, hazard identification, and method statement reviews",
"Oversee site inspections, audits, and incident investigations, and ensure corrective actions are implemented",
"Drive safety awareness, training programs, and toolbox talks across sites",
"Monitor HSE performance metrics and prepare reports for management and clients",
"Liaise with regulatory bodies, consultants, and client representatives on HSE matters",
"Promote a strong safety culture and continuous improvement across the organization.",
    ],
    requirements: [
      "BEng / BTech in Naval Architecture, Marine Engineering, or Ocean Engineering",
      "Minimum of 13 years’ HSE experience within the construction industry",
"Proven experience managing and leading an HSE team on construction projects",
"Strong knowledge of construction safety standards, risk management, and environmental compliance",
"Relevant HSE certifications (e.g., NEBOSH, IOSH, ISPON, OSHA, or equivalent)",
"Excellent leadership, communication, and reporting skills",
"Ability to work effectively in a fast-paced, multi-site construction environment",
"High level of professionalism, integrity, and attention to detail",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:trucretecareers@trucreteng.">trucretecareers@trucreteng.</a> using "HSE Manager – Construction as the subject of the mail.',
    salary: "Not specific",
    deadline: "Not specific",
  },
{
    id: "HEMM Technician (Excavators, Dozers, Payloader)",
    title: "HEMM Technician (Excavators, Dozers, Payloader)",
    location: "AkwaIbom , Delta, Imo and Rivers",
    type: "Full-time",
    seniority: "junior",
    summary:
      "The HEMM Technician will be responsible for the inspection, servicing, repair and preventive maintenance of heavy equipment, vehicles and construction machinery used in pipeline construction.",
    responsibilities: [
      "Perform routine servicing, inspection and troubleshooting of construction equipment.",
"Carry out preventive maintenance",
"Maintain services logs, equipment history sheets and breakdown reports.",
    ],
    requirements: [
      "A Diploma in any course or Trade Test Certificate",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:nnamdi.odili@energy-mgt.com ">nnamdi.odili@energy-mgt.com </a> using "HEMM Technician"  as the subject of the mail.',
    salary: "Not specific",
    deadline: "14th April, 2026.",
  },
{
    id: "IT Support Officer",
    title: "IT Support Officer",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "As the IT Support Officer at TeamAce Limited , you will provide technical support across the organization by maintaining IT infrastructure, resolving hardware and software issues, and supporting the implementation and management of IT infrastructure projects.",
    responsibilities: [
      "Provide technical support for hardware, software, network systems, and IT infrastructure across the organization",
"Install, configure, and maintain computer systems, servers, and network equipment",
"Troubleshoot and resolve technical issues while ensuring minimal disruption to business operations",
"Support IT infrastructure deployment during project execution and assist with system upgrades or migrations",
"Maintain IT documentation, system logs, and ensure adherence to IT security policies",
    ],
    requirements: [
      "Bachelor’s Degree in Computer Science, Information Technology, or related field",
"Minimum of 2 years experience in IT support, infrastructure support, or technical support roles",
"Professional certifications such as CompTIA A+, Network+, Cisco (CCNA), or Microsoft certifications are an advantage",
"Strong knowledge of network systems, operating systems, and IT infrastructure management",
"Excellent troubleshooting, communication, and problem-solving skills.",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="https://docs.google.com/forms/d/e/1FAIpQLSdputVpiz2XSM7wbYU_o1iDGw1PLFw3Pnw7hdnL-miwCHHDfg/viewform">HERE</a> to apply.',
    salary: "NGN 250,000 – 350,000 Monthly.",
    deadline: "10th April, 2026",
  },
{
    id: "HSE Officer",
    title: "HSE Officer",
    location: "Abuja",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "The HSE Manager is reponsible for investigating/recording incidents, accidents, complaints and cases of ill health on site.",
    responsibilities: [
      ".Investigating/recording incidents, accidents, complaints and cases of ill health on site",
"Undertaking risk assessments and site inspections.",
"Ensuring that equipment is installed correctly/safely.",
"Identifying potential hazards.",
"Determining ways of reducing risks.",
"Ensuring compliance with the health and safety policies stipulated by the company.",
"Writing internal health and safety policies/strategies.",
"Drawing-up safe operational practices and making necessary changes.",
"Writing reports, bulletins and newsletters on health and safety.",
"Providing health and safety meetings and training courses for employees.",
"Keeping up to date and ensuring compliance with current health and safety legislation",
    ],
    requirements: [
      "Bachelor`s or HND in Engineering- Mechanical, Electrial, Strucural, Civil or any related discipline.",
"3 - 5 years post NYSC experience as an HSE Officer in a construction environment.",
"Minimum Level 3 Health Safety and Environment (HSE) Certificate.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="recruitment@marandmor.com ">recruitment@marandmor.com </a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "Not specific",
  },
{
    id: "Reservoir Navigation Services Engineer",
    title: "Reservoir Navigation Services Engineer",
    location: "Port Harcourt, Rivers",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "The Lead Engineer or Scientist supports development through individual and teamwork. This level also requires the application of knowledge of materials, tools, processes, and products to solve problems, develop and execute objectives for self and others, and to effect short-term and some long-term business goals.",
    responsibilities: [
      "Running complex, high risk jobs",
"Building geosteering modelling",
"Coordinating expertise in one or more engineering and science disciplines across the technology project portfolio, assuring rigor is applied through the design and development processes.",
"Ensuring needed personnel skills and expertise are in place across the organization for the discipline.",
"Recognizing problems and providing solutions to mitigate or eliminate these",
"Working well with colleagues and customers across all businesses and cultures",
"Managing multiple project and/or deadlines",
    ],
    requirements: [
      "Have Bachelor's Degree with good industrial experience, with preference for an Engineering scientific or earth sciences discipline or relevant industry experience within product line",
"Show great experience of Reservoir Navigation Services or geo-steering",
"Have good interpersonal and leadership skills.",
"Demonstrate knowledge of drilling, LWD and wireline tools and measurements.",
"Demonstrate excellent proficiency and knowledge in RT log analysis",
"Have ability to manage multiple project and/or deadlines",
"Have good oral and written communication skills. Facility with other languages.",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="https://bakerhughes.wd5.myworkdayjobs.com/en-US/BakerHughes/job/NG-PORT-HARCOURT-125-TRANS-AMADI/Reservoir-Navigation-Services-Engineer_R156855-1?q=nigeria&utm_source=">HERE</a> to apply online',
    salary: "Not specific",
    deadline: "Not specific",
  },
{
    id: "IT Support Officer / Social Media Manager",
    title: "IT Support Officer / Social Media Manager",
    location: "Anthony, Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "Provide technical support for computers, printers, internet connectivity, and other IT equipment within the organization.",
    responsibilities: [
      "Install, configure, and maintain hardware, software, and network systems.",
"Troubleshoot and resolve IT-related issues reported by staff in a timely manner.",
"Manage company emails, user accounts, and basic system access controls.",
"Maintain and update the company’s website and digital platforms where applicable.",
"Create, schedule, and publish engaging content across the company’s social media platforms (e.g., Instagram, LinkedIn, Facebook, X).",
"Develop and implement social media strategies to increase brand awareness and engagement.",
"Must be able to design simple graphics, videos, and promotional materials for marketing campaigns.",
"Monitor social media accounts, respond to messages/comments, and manage online customer interactions professionally.",
"Track social media performance and prepare periodic analytics reports.",
"Support digital marketing initiatives such as online promotions, campaigns, and advertisements.",
"Ensure proper data backup, cybersecurity awareness, and safe IT practices within the organization.",
"Assist with technology setup for meetings, presentations, and company events.",
"Stay updated with new technology tools and social media trends relevant to the business.",
    ],
    requirements: [
      "Qualification: B.Sc / B.Tech in Computer Science or Information Technology",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:hiring@thyaura.com ">hiring@thyaura.com </a> using the job title as the subject of the mail.',
    salary: "N140,000 - N170,000 / month",
    deadline: "23rd March, 2026.",
  },
{
    id: "Senior Structural Engineer",
    title: "Senior Structural Engineer",
    location: "Somolu, Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "Sanni, Ojo& Partners Consulting Limited is a multidisciplinary engineering consultancy with over three decades of experience in civil, structural, and project management services. We are seeking more talented and experienced Senior Structural Engineer to join our existing team.The ideal candidate will lead the design and supervision of civil and structural engineering projects, ensuring compliance with safety, quality, and industry standards, while mentoring younger engineers and contributing to innovative, sustainable solutions.",
    responsibilities: [
      "Lead structural analysis and design of concrete and steel structures.",
"Supervise design documentation and project delivery.",
"Coordinate with architects, engineers, and clients.",
"Conduct site inspections and resolve structural issues.",
"Ensure adherence to codes and company quality standards.",
    ],
    requirements: [
      "B.Eng. / B.Sc. in Civil Engineering.",
"MNSE, MNISTRUCTE, COREN registrationis mandatory.",
"ProficiencyinProtaStructure,Autodesk Robot, or similar software.",
"Strong knowledge ofEurocodes,BS codes, and modern design practices.",
"Excellent communication, leadership, and teamwork skills.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:hr@sop-consulting.com ">hr@sop-consulting.com </a> using "Application – Senior Structural Engineer as the subject of the mail.',
    salary: "N400,000 - N500,000 / month",
    deadline: "9th April, 2026",
  },
  {
    id: "Graduate Software Engineer – Open Source and Linux",
    title: "Graduate Software Engineer – Open Source and Linux",
    location: "Lagos",
    type: "Remote",
    seniority: "Senior",
    summary:
      "Working towards mastery of key programming languages and Linux system knowledge",
    responsibilities: [
      "Shaping the roadmap for your product at global sprints every six months.",
"Focusing on design and user experience, even for developer tooling and command line apps.",
"Writing high quality, resilient and performant code, potentially serving millions of demanding daily users.",
"Engaging with users and the open source community through code reviews and issue trackers.",
"Responding to customer issues as a priority, develop an understanding of enterprise requirements.",
"Developing skills and awareness of security in software design and implementation.",
    ],
    requirements: [
      "Exceptional academic track record from both high school and university.",
"Undergraduate Degree in Computer Science, Business Informatics, Mathematics or another STEM discipline with programming courses",
"Confidence to get started and deliver high quality code in one of Python, Rust, C/C++, Golang, JavaScript or Java",
"Experience with Ubuntu or another Linux distribution",
"Track record of going above-and-beyond expectations to achieve outstanding results",
"Result-oriented and organized, with the drive to meet commitments",
"Personal projects in technology and software engineering beyond the curriculum",
"Professional written and spoken English",
"Excellent interpersonal skills, curiosity, flexibility, and accountability",
"Thoughtfulness, self-awareness and the ability to reflect and develop",
"Ability to travel internationally twice a year for company events up to two weeks long.",
"Nice-to-have skills: Upstream open source contributions, Packaging and Linux distribution contributions – Debian, Fedora, Arch, Nix or another, Leadership and organization skills, Presentation and writing skills and Business and commercial interests.",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="https://job-boards.greenhouse.io/canonicaljobs/jobs/7563956?gh_src=659932kh1us">HERE</a> to apply',
    salary: "Not specific",
    deadline: "Not specific",
  },
{
    id: "Graduate Sales / Business Development Intern",
    title: "Graduate Sales / Business Development Intern",
    location: "Nigeria",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "The Graduate Sales Intern will support the sales team in driving business growth by identifying potential clients, promoting company products or services, and assisting in closing sales opportunities. This role is designed for recent graduates who want to build a career in sales, business development, and client relationship management.",
    responsibilities: [
      "Assist the sales team in identifying and developing new business opportunities.",
"Support lead generation activities through cold calls, emails, and field visits.",
"Present and promote company products or services to prospective clients.",
"Maintain and update the sales database and customer records.",
"Assist in preparing sales presentations, proposals, and reports.",
"Participate in sales meetings, training sessions, and strategy discussions.",
"Conduct market research to identify potential clients and industry trends.",
"Support customer relationship management and follow-up with clients.",
"Achieve assigned sales targets and performance metrics.",
"Provide administrative support to the sales department when required.",
    ],
    requirements: [
      "Bachelor’s degree in Business Administration, Marketing, Economics, or a related field.",
"0–1 year of experience (NYSC members or fresh graduates are encouraged to apply).",
"Strong communication and interpersonal skills.",
"Basic understanding of sales and marketing principles.",
"Ability to work independently and as part of a team.",
"Good negotiation and persuasion skills.",
"Proficiency in Microsoft Office (Word, Excel, PowerPoint.",
    ],
    apply:
      'Interested and qualified candidates should click <a href="https://forms.gle/9io7mzxQau4ebLCM7">HERE</a> to apply',
    salary: "Not specific",
    deadline: "9th April, 2026",
  },
{
    id: "Network Operations Engineer (Shift-Based)",
    title: "Network Operations Engineer (Shift-Based)",
    location: "VI, Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We’re looking for a Network Operations Engineer to join our Network Operations Control Center (NOCC) ,the frontline team responsible for real-time monitoring, incident response, and remote fault resolution across our managed enterprise networks. If you thrive in a fast-paced NOC environment and enjoy solving complex network issues in real time, this role is for you.",
    responsibilities: [
      "Monitor NMS dashboards and acknowledge alerts within defined SLAs",
"Log, categorize, and manage incident tickets accurately",
"Perform remote troubleshooting to achieve high first-call resolution",
"Execute Zero Touch Provisioning (ZTP) for new deployments",
"Manage configuration backups and prevent configuration drift",
"Monitor fibre links and escalate physical faults when required",
"Coordinate with field teams (FOAS) for dispatch and resolution",
"Maintain detailed shift handovers and technical documentation.",
    ],
    requirements: [
      "3–5 years’ experience in NOC, network operations, or technical support",
"Strong understanding of TCP/IP, VLANs, DNS, DHCP, routing & switching",
"Hands-on experience with monitoring tools (PRTG, Zabbix, LibreNMS, SolarWinds, etc.)",
"CLI troubleshooting skills (ping, traceroute, diagnostics tools)",
"Experience in LAN/WAN and wireless troubleshooting",
"Mandatory Certification (at least one) of: CCNA or CompTIA Network+ or MikroTik MTCNA",
"Desirable: CCNP, Fortinet NSE, ITIL v4, Security+, CWNA",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:htominiakubie@ipnxnigeria.net ">htominiakubie@ipnxnigeria.net </a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "20th March, 2026",
  },
{
    id: "Site Building Support Intern  (NYSC)",
    title: "Site Building Support Intern (NYSC)",
    location: "Abuja",
    type: "Internship",
    seniority: "Senior",
    summary:
      "We are looking for a diligent and proactive Site Building Support Intern to join our team. The ideal candidate will assist in day-to-day site operations, project supervision, documentation, market surveys, procurement and coordination activities to ensure the successful completion of the oongoing building project.",
    responsibilities: [
      "Support site engineers, architects, and supervisors in managing daily construction activities.",
"Monitor site work progress and report observations or issues.",
"Assist in preparing and updating project documentation, reports, and schedules.",
"Ensure compliance with safety regulations and quality standards.",
"Coordinate logistics and materials on site under supervision.",
"Participate in meetings, inspections, and project planning sessions.",
"Assist with the procurement of building materials.",
    ],
    requirements: [
      "OND/Bachelor’s degree (in progress or completed) in Civil Engineering, Building Technology, Architecture, or a related field.",
"Basic understanding of construction processes, materials, and safety practices.",
"Strong attention to detail, organization, and willingness to learn.",
"Good communication and teamwork skills.",
"Ability to adapt to fieldwork conditions and work under supervision.",
    ],
    apply:
      'Interested and qualified candidates should click <a href="https://e4eapplication.paperform.co/">HERE</a> to apply.',
    salary: "Not specific",
    deadline: "5th April, 2026",
  },
{
    id: "Website / IT Support Officer ",
    title: "Website / IT Support Officer ",
    location: "Ikeja, Lagos",
    type: "Full-time",
    seniority: "Junior",
    summary:
      "The Website / IT Support Officer is responsible for maintaining the company’s website and providing technical support for computer systems, software, and IT equipment. The role ensures that all IT systems and the website run smoothly and efficiently.",
    responsibilities: [
      "Maintain and update the company website regularly.",
"Monitor website performance and fix technical issues.",
"Provide technical support to staff for computer hardware and software problems.",
"Install, configure, and maintain computer systems and applications.",
"Troubleshoot network, internet, and email issues.",
"Ensure website security and perform regular backups.",
"Assist in managing company databases and online platforms.",
"Set up computers, printers, and other IT equipment.",
"Keep records of IT issues and solutions.",
    ],
    requirements: [
      "Degree or diploma in Information Technology, Computer Science, or related field.",
"Basic knowledge of website management (WordPress, HTML, or similar tools).",
"Knowledge of computer hardware, software, and networking.",
"Good problem-solving and troubleshooting skills.",
"Strong communication and teamwork skills.",
"Ability to work independently and manage multiple task",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:hr@eandg.com.ng">hr@eandg.com.ngm</a> or <a href="mailto:eandg.tprecruiters@gmail.com ">eandg.tprecruiters@gmail.com </a> using the job title as the subject of the mail.',
    salary: "N350,000- N400,000 monthly.",
    deadline: "31st March, 2026",
  },
{
    id: "Operator – Utility",
    title: "Operator – Utility",
    location: "Sagamu, Ogun",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "Monitoring and operation of all utility equipment (Vapor compression & Vapor, Water treatment plant, Sewage treatment plant and Air compressor and HVAC system.).",
    responsibilities: [
      "Data recording.",
"Inspection and maintenance of the utility equipment.",
"Ability to work independently.",
"Prompt response to any complaint.",
"Maintaining of daily operational records.",
"Carrying out of daily inspection",
"Troubleshoots problem",
"Conducting of root cause analysis for breakdown.",
    ],
    requirements: [
      "Interested candidates should possess relevant qualifications with experience.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:robert.akpan@flexfilm.com">robert.akpan@flexfilm.com</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "6th April, 2026.",
  },
{
    id: "Quality Assurance Engineer (Aircraft Design)",
    title: "Quality Assurance Engineer (Aircraft Design)",
    location: "Abuja",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We are looking for a high-impact Quality Assurance (Aircraft Design Engineer) to lead the definition, sizing, and validation of our aircraft systems.",
    responsibilities: [
      "You will be responsible for translating mission requirements into feasible aircraft configurations during the conceptual and preliminary design phases. Beyond engineering, you will hold general supervisory responsibilities—overseeing daily team performance, ensuring 100% regulatory compliance, and maintaining a culture of quality.",
"Conceptual Design: Translate mission requirements into aircraft layouts, perform initial sizing, and generate constraint diagrams.",
"Performance & Stability: Predict performance across the flight envelope and ensure static/dynamic stability and tail surface sizing.",
"Aerodynamics & Structures: Estimate lift/drag characteristics and perform first-order structural sizing and load path definition.",
"Weight & Balance: Build and maintain detailed weight breakdowns and track CG locations throughout the design cycle.",
"System Integration: Size and integrate propulsion systems and run multidisciplinary trade studies to resolve conflicting requirements.",
"Manufacturing & Quality: Ensure Design for Manufacturing (DFM) and 100% adherence to aviation regulations (NCAA, FAA).",
"Leadership: Supervise daily stand-ups, track deliverables, evaluate team performance, and oversee real-time quality monitoring systems.",
    ],
    requirements: [
      "Design Expertise: Mastery of aircraft configuration theory, performance equations, and atmosphere models.",
"Technical Modeling: Proficiency in solid modeling (CATIA, SolidWorks) and numerical modeling (MATLAB, Python, or Excel).",
"Analytical Strength: Deep understanding of static margins, stability derivatives, and aerodynamic theory (including CFD literacy).",
"Structural Knowledge: Familiarity with classical beam/shell theory, FEM awareness, and aerospace materials/tolerances.",
"Leadership Mindset: Strong engineering judgment, systems thinking, and a commitment to continuous safety training and cybersecurity frameworks",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:recruitment@uniccongroup.com">recruitment@uniccongroup.com</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "Not specific",
  },
{
    id: "Front-end Developer",
    title: "Front-end Developer",
    location: "Lagos",
    type: "Remote",
    seniority: "Senior",
    summary:
      "Collaborate with designers and backend developers to create interactive and engaging web/mobile applications.",
    responsibilities: [
      "Collaborate with designers and backend developers to create interactive and engaging web/mobile applications.",
"Build reusable, maintainable, and efficient front-end/mobile code.",
"Ensure the technical feasibility of UI/UX designs.",
"Optimize applications for maximum speed and scalability.",
"Continuously improve user experience with a focus on quality and usability.",
    ],
    requirements: [
      "Experience with front-end frameworks like React, Angular, or Vue.js.",
"Familiarity with version control systems (e.g., Git).",
"Understanding of responsive design and mobile-first web development.",
"Knowledge of web performance optimization techniques.",
"Strong problem-solving skills and attention to detail.",
"Nice to Have Experience with RESTful APIs.and Agile development methodologies",
    ],
    apply:
      'Interested and qualified candidates should send their their resume and portfolio link  to: <a href="mailto:topwebtec@gmail.com">topwebtec@gmail.com</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "17th March, 2026",
  },
{
    id: "Facilities and Premises Officer",
    title: "Facilities and Premises Officer",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We are looking for a Facilities and Premises Officer to oversee the day-to-day maintenance, safety, and functionality of our premises. This role ensures that facilities are well-managed, clean, secure, and supportive of organizational activities. You will ensure our premises are well-maintained, safe, and fully operational.",
    responsibilities: [
      "Oversee day-to-day management of the estate, office premises, and related facilities.",
"Supervise repairs, maintenance, and cleaning of buildings, grounds, and equipment.",
"Coordinate and monitor contractors, artisans, and vendors (plumbers, electricians, cleaners, security, etc.).",
"Conduct routine inspections and resolve facility-related issues promptly.",
"Ensure utilities (electricity, water, waste disposal, generators, etc.) are functional and bills are paid on time.",
"Maintain accurate facility records including logs, contracts, and reports.",
"Ensure compliance with health, safety, security, and tenancy regulations.",
"Manage emergency repairs and provide quick solutions to facility problems.",
"Support office readiness and ensure spaces are functional for operations.",
"Source quotes for goods and services, manage budgets, and coordinate facility improvement projects.",
"Implement energy conservation and cost-saving measures.",
"Manage tenant relations, tenancy agreements, and compliance.",
"Oversee short-let bookings and activities, ensuring cleanliness, readiness, and smooth guest experiences for local and international clients.",
    ],
    requirements: [
      "HND / B.Sc in Facility Management, Engineering, Estate Management, or related field.",
"Minimum of 2 years experience in facility/estate management.",
"Strong organizational and supervisory skills.",
"Ability to supervise and coordinate with vendors, contractors, and staff.",
"Good problem-solving skills; ability to respond to emergencies and unforeseen issues.",
"Knowledge of safety, health and security standards/regulations in Nigeria.",
    ],
    apply:
      'Interested and qualified candidates should send their CV and Cover Letter to: <a href="mailto:communityoutreach3@aol.com">communityoutreach3@aol.com</a> and cc <a href="mailto: aamatthewint2@aol.com"> aamatthewint2@aol.com</a> using the job title as the subject of the mail.',
    salary: "N150,000 / month",
    deadline: "31st March, 2026",
  },
{
    id: "Chief Technical Officer (CTO)",
    title: "Chief Technical Officer (CTO)",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "The Chief Technical Officer (CTO) will be responsible for leading the organization’s technology strategy, overseeing software development, and ensuring the delivery of secure, scalable, and high-performing digital platforms. The role requires a strategic technology leader who can align engineering initiatives with business objectives while building and managing high-performing technical teams.",
    responsibilities: [
      "Define and execute the organization’s technology strategy in alignment with business goals and growth plans.",
"Lead and manage engineering, software development, infrastructure, and technology teams.",
"Design scalable system architectures and ensure the reliability, performance, and security of all technology platforms.",
"Oversee the development, deployment, and maintenance of software products and digital solutions.",
"Establish best practices in software development, DevOps, cybersecurity, and system monitoring.",
"Drive innovation by identifying and implementing emerging technologies that enhance business capabilities.",
"Manage technology budgets, vendor relationships, and third-party technology partnerships.",
"Ensure compliance with data protection regulations, security standards, and industry best practices.",
"Collaborate with executive leadership to translate business requirements into technology solutions.",
"Mentor and develop engineering teams while fostering a culture of innovation and continuous improvement.",
    ],
    requirements: [
      "Bachelor’s Degree in Computer Science, Software Engineering, Information Technology, or a related field.",
"Master’s Degree in Technology Management or Business Administration is an added advantage.",
"10+ years of experience in software development or technology leadership roles.",
"Minimum of 5 years in a senior leadership or management position overseeing engineering teams.",
"Strong experience with cloud infrastructure, software architecture, and scalable system design.",
"Proven ability to build and lead high-performing engineering teams.",
"Strong understanding of cybersecurity practices, system reliability, and technology governance.",
"Excellent leadership, communication, and strategic decision-making skills.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:Ayomide.lala@kennediaconsulting.net">Ayomide.lala@kennediaconsulting.net</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "6th April, 2026",
  },
  {
    id: "Project Manager – Integrated & Solutions",
    title: "Project Manager – Integrated & Solutions",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "Acting as a strong, committed HSE Leader and provides a full HSE Leadership to all parties involved in the Project through the implementation of Baker Hughes HSE Management system and applicable customer’s HSE requirements. Promotes Stop Work Authority & speaking up culture at the project.",
    responsibilities: [
      "Leading all elements of the project including Baker Hughes products and services, contracted parties and client interfaces.",
"Managing for “on time’ delivery, performance Improvement, and incremental revenue through upsell strategies, additional pull through of additional products or services.",
"Owning the overall customer deliverables by having the responsibility for the Integrated Solutions compliance, financial KPI’s, service delivery and HSE performance.",
"Being responsible for all aspects of the financial performance of the project.",
"Leading the support for the sales team’s development of any future related opportunity pipelines.",
"Aligning cross product line strategies to the Integrated Solutions project deliverables.",
"Promoting and driving implementation of Remote Operations in the projects as applicable.",
"Managing the core Project Management Team, and indirectly all other project assigned personnel.",
"Managing multiple products and services across multiple wellsites/rigs, often in complex contractual arrangements.",
"Developing and managing the project schedule at the top level and applies solutions to both leading and lagging situations as well as to unforeseen and predicted events.",
"Appling Baker Hughes specific group (Integrated Solutions) Management System processes and procedures to the project, as well as any mandated software solutions that are applicable.",
"Utilizing project management methodology in daily working practice, additionally encouraging team members by example.",
    ],
    requirements: [
      "Have a Bachelor’s Degree in engineering or scientific discipline from an accredited university or relevant industry experience.",
"Have a minimum of 10+ years of experience in relevant industry (wellbore construction, completions, wellbore intervention, P&A etc.) with a minimum of 5 years as a project manager.",
"Well Control awareness is required. Well Control Certification would be an advantage.",
"Experience managing drilling and completions operations and with strong operational and technical capabilities.",
"Must be experienced managing change and assessing risk and financial implications of change, inclusive of managing Variation Requests.",
"Having a good leadership, excellent interpersonal, influencing and planning skills will be considered necessary for this position.",
"Have an excellent English oral and written communications skills, including ability to organize meetings and distributing accurate and succinct minutes of meetings.",
"Be experienced needs to include managing multiple product line P&L (Profit and Loss management) and experience managing multiple simultaneous rig/site operations.",
"Be skilled in functional use of MS Office Suite, with MS Project familiarity is required.",
"Ability to manage, develop, coach and mentor high level teams across organizational boundaries is required.",
"PMP (Project Management Professional) certification would be considered an advantage.",
"Proven personnel development skills will be required in this role.",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="https://careers.bakerhughes.com/global/en/job/R159441/Project-Manager-Integrated-Solutions">HERE</a> to apply.',
    salary: "Not specific",
    deadline: "Not specific",
},
{
    id: "Digital Intern",
    title: "Digital Intern",
    location: "Lagos",
    type: "Remote",
    seniority: ": Internship",
    summary:
      "IICOCECE is seeking creative and motivated Digital Interns to support our online marketing and brand visibility efforts. The ideal candidate will assist in managing social media platforms, creating engaging digital content, and supporting marketing campaigns that promote the company’s properties and investment opportunities.",
    responsibilities: [
      "Assist in managing the company’s social media platforms (Facebook,Instagram, LinkedIn, etc.).",
"Create and post engaging content to promote properties and investment opportunities.",
"Assist in designing simple promotional materials, graphics, and digital adverts.",
"Monitor social media messages, comments, and inquiries and respond appropriately.",
"Support the digital marketing team in planning and executing online marketing campaigns.",
"Help update the company’s website with property listings, news, and announcements.",
"Conduct basic online research on market trends, competitors, and digital strategies.",
"Track and report engagement on social media posts and digital campaigns.",
"Assist in taking photos or videos of properties for marketing purposes.",
"Perform other digital and marketing tasks as assigned by management.",
    ],
    requirements: [
      "Minimum of OND / HND / Bachelor’s Degree (or currently studying) in Marketing, Mass Communication, Media Studies, ICT, or a related field.",
"Basic knowledge of social media marketing and digital communication.",
"Familiarity with Canva or other design tools is an added advantage.",
"Good communication and creativity skills.",
"Basic knowledge of photography, video editing, or graphic design is an advantage.",
"Ability to learn quickly and work in a fast-paced environment.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:digitaltransformation@revenstrat.com">digitaltransformation@revenstrat.com</a> using “Digital Intern” as the subject of the mail.',
salary: "N30,000",
    deadline: "20th April, 2026",
  },
{
    id: "FTTH Project Design Engineer",
    title: "FTTH Project Design Engineer",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "The FTTH Project Design Engineer coordinate with site engineers, subcontractors, clients and subcontractors and is responsible for reviewing and updating subcontractors’ design documents.",
    responsibilities: [
      "Responsible for coordinating with clients and subcontractors, and ensuring subcontractors complete survey and design tasks on time.",
      "Responsible for reviewing and updating subcontractors’ design documents.",
      "Coordinate with site engineers and subcontractors to prepare as-built documentation",
    ],
    requirements: [
      "Bachelor’s Degree in Electronics, Telecommunications, or related field",
"Minimum of 2 years of FTTH design-related work experience",
"Proficient in design tools such as AutoCAD and Google Earth",
"Proficient in Microsoft Office software.",
    ],
    apply:
      'Interested and qualified candidates can apply online by clicking: <a href="https://www.linkedin.com/jobs/view/4376274721/">HERE</a>',
    salary: "Not specific",
    deadline: "Not specific",
},
{
    id: "HSE Coordinator",
    title: "HSE Coordinator",
    location: "Amadi Base, Rivers",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "Assist QHSE Manager in ensuring continuous improvement of operational safety management knowledge and application within the organization.",
    responsibilities: [
      "Implementation of pre-task planning tools: (Job Safety Analysis, Toolbox Talk, etc.).",
"Implementation of proactive tools (Bsafe Cards, Stop Work, Near Miss reporting.)",
" Assist in Shorebase induction, delivery, and coaching including Safety Takes Me Home deployment.",
"Participate in day-to-day incident management, including incident investigation, as delegated by the HSE manager.",
"Conducting ‘QHSE campaigns’ for onshore facilities and assisting in campaign application onboard vessels.",
"Maintain shore-based incidents databases including Incident reports, Investigation reports, medical reports (if applicable), Witness statements, Taproot® Snap Charts, Corrective action plans, Photos, drawings/sketches, etc.",
"Collate all general and client-specific monthly and weekly QHSE statistics for all vessels working in Nigeria (BINL and affiliates). ",
"Maintain shore medical facility including first aid box.",
"Update all records including HSE statistics on BINL and BOURBON portals, offshore visits, client meetings, etc. ",
"Conduct Risk Assessment at shore base locations and develop actions plan for effective close-out of any identified gaps and updating the JSAs whenever required.",
    ],
    requirements: [
      "BSc Social Sciences or related field with relevant HSE certifications. ",
"A Master’s Degree in a relevant field will be an added advantage.",
"Work Experience for 5 years and above minimum experience in HSE in a multinational",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="https://bourbon-career.talent-soft.com/job/job-hse-coordinator-m-f_2152.aspx?utm_source=">HERE</a> to apply online',
    salary: "Not specific",
    deadline: "Not specific",
},
{
    id: "Project / Field Engineer",
    title: "Project / Field Engineer",
    location: "Port Harcourt, Rivers",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We are seeking a highly qualified Project Engineer to join our team. As a Project / Field Engineer, you will play a crucial role in overseeing the technical and practical execution of engineering projects offsite and on-site. You will also be responsible for ensuring projects are completed safely, on time, within budget, and according to design specifications.",
    responsibilities: [
      "Prepare, schedule, coordinate and monitor the assigned engineering projects",
"Responsible for scheduling, conducting and coordinating the technical and managerial aspect of projects.",
"Monitoring project status reports and change orders.",
"Accountable for the successful completion of engineering projects.",
"Requires extensive regular contact with assigned project clients.",
"Assist in the preparation of engineering projects proposals.",
"Budget monitoring and trend tracking.",
"Participate in Client / Contractor meetings and resolving Client / Engineering and management project issues.",
"Keep an eye on all relevant safety objectives and legal requirements.",
"Interpret clients requirements.",
"Identify engineering problems and ensure solutions are implemented.",
"Evaluate, organize and prioritize workload within a schedule.",
"Liaise with third party contractors to ensure all equipment are fit for purpose.",
"Take responsibility for a team of engineers.",
"Take full responsibility for any assigned project from commencement to completion whether on shoe, offshore or swamp.",
    ],
    requirements: [
      "B.Sc. / B.Eng. / HND in engineering field. A Masters’ degree will be an added advantage with Experience: 3–5 years post qualification / (NYSC) experience, COREN / NSE membership is an added advantage",
"Proven experience working in a Project management role in manufacturing, construction and / or oil and gas industries",
"Verifiable experience in the use of MS Office packages.",
"HSE Level 3 minimum",
"Should reside in Port Harcourt or willing to relocate.",
"Should have skills like,: Microsoft Office Project, Primavera, Ability to use initiative, The ability to explain design and plans clearly and Confident decision-making ability",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:offixrecruit@gmail.com ">offixrecruit@gmail.com </a> using “Project / Field Engineer” title as the subject of the mail.',
    salary: "Not specific",
    deadline: "28th march, 2026",
},
    {
    id: "Medical Laboratory Scientist",
    title: "Medical Laboratory Scientist",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We are looking for a professional who is passionate about precision in laboratory testing, quality assurance, and contributing to high-standard healthcare delivery . We are seeking a competent, detail-oriented, and experienced Medical Laboratory Scientist to strengthen our diagnostics team. We are dedicated to providing accurate, reliable, and timely laboratory results that directly support clinical diagnosis, treatment decisions, and patient care excellence.",
    responsibilities: [
      "Conduct a comprehensive range of laboratory investigations in hematology, clinical chemistry, microbiology, parasitology, immunology, serology, coagulation, and urinalysis.",
"Receive, process, and analyze various clinical specimens (blood, urine, body fluids, swabs, tissues, etc.) using both manual and automated techniques.",
"Operate, calibrate, maintain, and perform daily/periodic quality control on laboratory analyzers and equipment.",
"Interpret test results, verify abnormal findings, and escalate critical values to clinicians in a timely manner.",
"Ensure strict compliance with infection prevention and control protocols, biohazard waste management, and laboratory safety standards.",
"Maintain accurate, complete, and confidential records of all tests, results, and procedures in the laboratory information system (LIS).",
"Assist in reagent preparation, inventory management, stock monitoring, and ordering of laboratory consumables.",
"Support continuous improvement initiatives, equipment troubleshooting, and training of junior staff or interns where applicable.",
"Collaborate with pathologists, clinicians, and other healthcare professionals to ensure diagnostic accuracy and optimal patient outcomes.",
    ],
    requirements: [
      "Bachelor of Medical Laboratory Science (BMLS) Degree from a recognized and accredited institution..",
"Full registration and valid/current practicing license from the Medical Laboratory Science Council of Nigeria (MLSCN)..",
"2–4 years of post-qualification experience in a busy hospital laboratory, diagnostic center, or private pathology lab..",
"Hands-on experience with automated analyzers (hematology, chemistry, immunoassay), microbiology culture techniques, and blood banking procedures is highly desirable..",
"Strong technical proficiency across multiple laboratory disciplines with excellent hands-on skills.",
"Ability to work efficiently in a high-volume environment while maintaining accuracy under pressure.",
"Strong organizational skills and commitment to documentation, traceability, and result integrity.",
"Effective communication skills for clear reporting of results and professional interaction with clinical teams.",
"Dedication to ethical practice, patient confidentiality, safety, and lifelong learning.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:Admin@clinixhealthcare.com.ng">Admin@clinixhealthcare.com.ng</a> and copy to: <a href="mailto:hr@clinixhealthcare.com.ng"> hr@clinixhealthcare.com.ng</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "Not specific",
},
{
    id: "Field Operator III",
    title: "Field Operator III",
    location: "EDOP Platform, Akwa Ibom",
    type: "Contract",
    seniority: "Junior",
    summary:
      "Operate equipment and wells by applying operating and safety procedures and guidelines to meet daily operational plan, reduce equipment failure and efficient resources administration.",
    responsibilities: [
      "Responsible to implement on daily work objectives, housekeeping, safety, health, environmental and security",
"Active participation on daily toolbox meetings and regular, reported safety meetings",
"Identify and implement corrective and optimization actions by the continuous surveillance of wells and equipment to ensure reliable, efficient and safe operational conditions",
"Function as Equipment Care Technician, and routinely use Maintenance skills in performing simple maintenance activities",
"Report when the alarm, emergency or emergency shutdown system is out of service",
"Provide detailed, clear and accurate information when changing shift, to guarantee that unit conditions are updated and ensure operations continuity",
"Coordinate, control and monitor maintenance jobs according with the corrective, predictive and preventive planning",
"Report continuously in the log book all relevant operational events and abnormal situations or deviation occurred in the work area, equipment or personnel",
"Take samples of products for laboratory analysis and execute field laboratory tests",
"Active participation on emergency response activities",
"Report incidents internally and escalate awareness as per the Incident Reporting Guidelines",
"Ensure that Operations Shift Supervisor is informed and consulted about operations activities",
"Ensure good communication across the work team so that issues / actions can be adequately addressed",
"Provide the basic facts concerning well producing problems, current production rates, and current condition of the well",
"Ensure that the well problem diagnostics are thorough and complete before requesting Well Work intervention operations",
    ],
    requirements: [
      "Completed secondary education and worked previously as a Field Technician",
      "High standard of safety, Health, Environment apttitude and cultivates the same in others",
      "Extensive knowledge and/or experience of pipeline operations",
	"Entensive knowledge of Project Phylosophy and Design Specifications.",
	"Strong communication (oral and written)",
    ],
    apply:
      'Interested and qualified candidates should send their CV in MS Word to: <a href="mailto:job@abnl.net">job@abnl.net</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "16th March, 2026",
},
{
    id: "Product Marketing Manager",
    title: "Product Marketing Manager",
    location: "Lagos",
    type: "Remote",
    seniority: "Senior",
    summary:
      "The Naval Architect is responsible for the design, development, and optimization of marine vessels and offshore structures.",
    responsibilities: [
      "You’ll own the GTM strategy for key products, shaping messaging and positioning that speaks to developers and enterprise buyers alike.",
"You’ll collaborate cross-functionally with product management, sales, regional marketing, content, and partner marketing teams to bring campaigns to life.",
"You’ll get creative, crafting compelling advertising, launch plans, and campaigns that make our products stand out in a competitive landscape.",
"You’ll measure impact, using data to refine messaging, optimize marketing funnels, and drive customer engagement.",
"You’ll be part of a truly global team, working with colleagues in over 85 countries in a fully remote, high-performance environment.",
"Develop and execute go-to-market (GTM) strategies for a range of products.",
"Lead messaging and positioning efforts ensuring our products stand out in a competitive market.",
"Lead content planning with product managers —from website copy to whitepapers, blogs, and sales enablement materials.",
"Collaborate on marketing campaigns, partnering with regional marketing teams to execute integrated campaigns that drive pipeline growth.",
"Launch new products and features, leading cross-functional teams to drive awareness and adoption.",
"Run competitive analysis, staying ahead of market trends and evolving our positioning accordingly.",
"Support the customer success team on driving customer engagement and growth, working on strategies to upsell and cross-sell across our customer base.",
"Plan and execute global events, live webinars, and community meetups that align with our GTM priorities.",
    ],
    requirements: [
      "A passion for technology and open source—you get excited about innovation, software, and community-driven development.",
"Strong storytelling skills—you know how to craft messaging that resonates with both technical and business audiences.",
"Growth mindset—someone who thrives on experimentation, learning, and continuous improvement.",
"Excellent communication skills, both written and verbal.",
"Data-driven mindset, using insights to refine strategies and improve performance.",
"Experience in product marketing for enterprise software, cloud, DevOps, or open-source solutions.",
"Experience with demand generation, understanding how to translate GTM strategies into pipeline growth.",
"Comfort working cross-functionally with product, sales, partners, and marketing teams.",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="https://job-boards.greenhouse.io/canonicaljobs/jobs/7619278?gh_src=jpx8xfro1us">HERE</a> to apply online.',
    salary: "Your base pay will depend on various factors including your geographical location, level of experience, knowledge and skills. Please note that additional benefits may apply depending on the work location and, for more information on these, please ask your Talent Partner.",
    deadline: "Not specific",
},
{
    id: "Assistant QHSE Manager",
    title: "Assistant QHSE Manager",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "A Marine Logistics provider is seeking a highly motivated and experienced Assistant QHSE Manager to champion and drive continual improvement in operational safety management across our marine fleet and onshore operations. The Ideal candidate will be responsible for implementing the company’s  HSE plan, leading compliance initiatives, and ensuring a safe, efficient, and legally compliant working environment in alignment with international and company standards. The position is primarily based in Lagos.",
    responsibilities: [
      "Drive continual, measurable, and sustainable improvement in HSE performance in line with  strategic objectives.",
"Investigate incidents thoroughly, identify root causes, and implement corrective actions to prevent recurrence.",
"Maintain and monitor the Offshore Vessel Management Self-Assessment (OVMSA) system, ensuring full compliance with IOGP standards.",
"Monitor and close out OVID inspection non-conformances across vessels.",
"Develop and implement the yearly QHSE plan for marine and onshore operations.",
"Collect, analyze, and report HSE statistics, identifying trends and developing proactive measures to minimize incidents.",
"Conduct annual reviews of the Safety Management System to ensure alignment with international best practices.",
"Lead HSE campaigns and trainings across the organization, both offshore and onshore.",
"Establish and monitor emergency preparedness plans through drills and training programs.",
    ],
    requirements: [
      "Bachelor’s Degree or equivalent from a reputable institution with inimum of 5 years’ work experience in the oil and gas industry, with at least 2 years in a similar HSE function.",
"NEBOSH IGC or Diploma (preferred).",
"Master’s degree in a relevant field (an added advantage).",
"Strong knowledge of HSE regulations and best practices in the oil and gas/marine sector.",
"Excellent analytical, incident investigation, and reporting skills.",
"Effective communication and leadership abilities.",
"Ability to manage and implement structured safety programs across multi-site operations.",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="">HERE</a> to apply.',
    salary: "Not specific",
    deadline: "2Oth March, 2026",
    },
    {
    id: "Surveyor",
    title: "Surveyor",
    location: "Ode-Remo – Abeokuta, Ogun",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We are seeking a skilled and experienced Surveyor with a minimum of 6 years of professional experience in land surveying. The ideal candidate must be familiar with the Lands Department in Abeokuta and understand the processes involved in land documentation, approvals, and boundary verification. The Surveyor will be responsible for conducting land measurements, preparing survey plans, and ensuring compliance with regulatory requirements.",
    responsibilities: [
      "Carry out land and property surveys for acquisition, development, and documentation.",
"Prepare survey plans, maps, and technical reports for land registration and approvals.",
"Liaise with the Lands Department in Abeokuta for survey plan submissions, charting, and other regulatory processes.",
"Conduct site inspections and boundary verification to ensure accurate land measurements.",
"Operate and maintain survey equipment such as Total Station, GPS, and other surveying tools.",
"Assist in land documentation and title processing where required.",
"Work closely with engineers, architects, and project teams to provide accurate survey data",
"Maintain proper survey records and documentation for company projects.",
"Ensure all survey activities comply with government regulations and professional standards.",
    ],
    requirements: [
      "HND or Bachelor’s Degree in Surveying, Geomatics, or a related field with a minimum of 6 years of proven experience in land surveying.",
"Must be familiar with the Lands Department procedures in Abeokuta.",
"Strong knowledge of survey equipment such as GPS, Total Station, and mapping software.",
"Good understanding of land documentation and boundary identification.",
"Excellent communication and teamwork skills.",
"Ability to work independently and handle multiple projects effectively.",
"Skills needed are: Land Surveying and Mapping, Boundary Identification, Survey Equipment Operation, Land Documentation Processes, Data Analysis and Reporting and Team Collaboration",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:ninestars.recruitment@yahoo.com">ninestars.recruitment@yahoo.com</a> using “Surveyor Application”  as the subject of the mail.',
    salary: "N300,000 – N400,000 / month",
    deadline: "31st March, 2026",
    },
    {
    id: "Naval-Architect",
    title: "Naval Architect",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "The Naval Architect is responsible for the design, development, and optimization of marine vessels and offshore structures.",
    responsibilities: [
      "Design end-to-end user experiences",
      "Mentor junior designers",
      "Collaborate with PMs and engineers",
    ],
    requirements: [
      "BEng / BTech in Naval Architecture, Marine Engineering, or Ocean Engineering",
      "Minimum 5+ years’ experience in vessel design, structural analysis, or shipbuilding projects",
      "Proficiency in marine design and analysis software (AutoCAD, Rhino, Maxsurf, ANSYS, or equivalent)",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:hr@russelsmithgroup.com">hr@russelsmithgroup.com</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "Not specific",
  },
];
