export type Job = {
  id: string;
  title: string;
  location: string;
  type: string;
  seniority?: string;
  summary: string;
  responsibilities: string[];
  requirements: string[];
  apply: string; 
  salary: string;
  deadline: string;
}

export const jobs: Job[] = [
  {
    id: "Project Manager – Integrated & Solutions",
    title: "Project Manager – Integrated & Solutions",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "Acting as a strong, committed HSE Leader and provides a full HSE Leadership to all parties involved in the Project through the implementation of Baker Hughes HSE Management system and applicable customer’s HSE requirements. Promotes Stop Work Authority & speaking up culture at the project.",
    responsibilities: [
      "Leading all elements of the project including Baker Hughes products and services, contracted parties and client interfaces.",
"Managing for “on time’ delivery, performance Improvement, and incremental revenue through upsell strategies, additional pull through of additional products or services.",
"Owning the overall customer deliverables by having the responsibility for the Integrated Solutions compliance, financial KPI’s, service delivery and HSE performance.",
"Being responsible for all aspects of the financial performance of the project.",
"Leading the support for the sales team’s development of any future related opportunity pipelines.",
"Aligning cross product line strategies to the Integrated Solutions project deliverables.",
"Promoting and driving implementation of Remote Operations in the projects as applicable.",
"Managing the core Project Management Team, and indirectly all other project assigned personnel.",
"Managing multiple products and services across multiple wellsites/rigs, often in complex contractual arrangements.",
"Developing and managing the project schedule at the top level and applies solutions to both leading and lagging situations as well as to unforeseen and predicted events.",
"Appling Baker Hughes specific group (Integrated Solutions) Management System processes and procedures to the project, as well as any mandated software solutions that are applicable.",
"Utilizing project management methodology in daily working practice, additionally encouraging team members by example.",
    ],
    requirements: [
      "Have a Bachelor’s Degree in engineering or scientific discipline from an accredited university or relevant industry experience.",
"Have a minimum of 10+ years of experience in relevant industry (wellbore construction, completions, wellbore intervention, P&A etc.) with a minimum of 5 years as a project manager.",
"Well Control awareness is required. Well Control Certification would be an advantage.",
"Experience managing drilling and completions operations and with strong operational and technical capabilities.",
"Must be experienced managing change and assessing risk and financial implications of change, inclusive of managing Variation Requests.",
"Having a good leadership, excellent interpersonal, influencing and planning skills will be considered necessary for this position.",
"Have an excellent English oral and written communications skills, including ability to organize meetings and distributing accurate and succinct minutes of meetings.",
"Be experienced needs to include managing multiple product line P&L (Profit and Loss management) and experience managing multiple simultaneous rig/site operations.",
"Be skilled in functional use of MS Office Suite, with MS Project familiarity is required.",
"Ability to manage, develop, coach and mentor high level teams across organizational boundaries is required.",
"PMP (Project Management Professional) certification would be considered an advantage.",
"Proven personnel development skills will be required in this role.",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="https://careers.bakerhughes.com/global/en/job/R159441/Project-Manager-Integrated-Solutions">HERE</a> to apply.',
    salary: "Not specific",
    deadline: "Not specific",
},
{
    id: "Digital Intern",
    title: "Digital Intern",
    location: "Lagos",
    type: "Remote",
    seniority: ": Internship",
    summary:
      "IICOCECE is seeking creative and motivated Digital Interns to support our online marketing and brand visibility efforts. The ideal candidate will assist in managing social media platforms, creating engaging digital content, and supporting marketing campaigns that promote the company’s properties and investment opportunities.",
    responsibilities: [
      "Assist in managing the company’s social media platforms (Facebook,Instagram, LinkedIn, etc.).",
"Create and post engaging content to promote properties and investment opportunities.",
"Assist in designing simple promotional materials, graphics, and digital adverts.",
"Monitor social media messages, comments, and inquiries and respond appropriately.",
"Support the digital marketing team in planning and executing online marketing campaigns.",
"Help update the company’s website with property listings, news, and announcements.",
"Conduct basic online research on market trends, competitors, and digital strategies.",
"Track and report engagement on social media posts and digital campaigns.",
"Assist in taking photos or videos of properties for marketing purposes.",
"Perform other digital and marketing tasks as assigned by management.",
    ],
    requirements: [
      "Minimum of OND / HND / Bachelor’s Degree (or currently studying) in Marketing, Mass Communication, Media Studies, ICT, or a related field.",
"Basic knowledge of social media marketing and digital communication.",
"Familiarity with Canva or other design tools is an added advantage.",
"Good communication and creativity skills.",
"Basic knowledge of photography, video editing, or graphic design is an advantage.",
"Ability to learn quickly and work in a fast-paced environment.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:digitaltransformation@revenstrat.com">digitaltransformation@revenstrat.com</a> using “Digital Intern” as the subject of the mail.',
salary: "N30,000",
    deadline: "20th April, 2026",
  },
{
    id: "FTTH Project Design Engineer",
    title: "FTTH Project Design Engineer",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "The FTTH Project Design Engineer coordinate with site engineers, subcontractors, clients and subcontractors and is responsible for reviewing and updating subcontractors’ design documents.",
    responsibilities: [
      "Responsible for coordinating with clients and subcontractors, and ensuring subcontractors complete survey and design tasks on time.",
      "Responsible for reviewing and updating subcontractors’ design documents.",
      "Coordinate with site engineers and subcontractors to prepare as-built documentation",
    ],
    requirements: [
      "Bachelor’s Degree in Electronics, Telecommunications, or related field",
"Minimum of 2 years of FTTH design-related work experience",
"Proficient in design tools such as AutoCAD and Google Earth",
"Proficient in Microsoft Office software.",
    ],
    apply:
      'Interested and qualified candidates can apply online by clicking: <a href="https://www.linkedin.com/jobs/view/4376274721/">HERE</a>',
    salary: "Not specific",
    deadline: "Not specific",
},
{
    id: "HSE Coordinator",
    title: "HSE Coordinator",
    location: "Amadi Base, Rivers",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "Assist QHSE Manager in ensuring continuous improvement of operational safety management knowledge and application within the organization.",
    responsibilities: [
      "Implementation of pre-task planning tools: (Job Safety Analysis, Toolbox Talk, etc.).",
"Implementation of proactive tools (Bsafe Cards, Stop Work, Near Miss reporting.)",
" Assist in Shorebase induction, delivery, and coaching including Safety Takes Me Home deployment.",
"Participate in day-to-day incident management, including incident investigation, as delegated by the HSE manager.",
"Conducting ‘QHSE campaigns’ for onshore facilities and assisting in campaign application onboard vessels.",
"Maintain shore-based incidents databases including Incident reports, Investigation reports, medical reports (if applicable), Witness statements, Taproot® Snap Charts, Corrective action plans, Photos, drawings/sketches, etc.",
"Collate all general and client-specific monthly and weekly QHSE statistics for all vessels working in Nigeria (BINL and affiliates). ",
"Maintain shore medical facility including first aid box.",
"Update all records including HSE statistics on BINL and BOURBON portals, offshore visits, client meetings, etc. ",
"Conduct Risk Assessment at shore base locations and develop actions plan for effective close-out of any identified gaps and updating the JSAs whenever required.",
    ],
    requirements: [
      "BSc Social Sciences or related field with relevant HSE certifications. ",
"A Master’s Degree in a relevant field will be an added advantage.",
"Work Experience for 5 years and above minimum experience in HSE in a multinational",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="https://bourbon-career.talent-soft.com/job/job-hse-coordinator-m-f_2152.aspx?utm_source=">HERE</a> to apply online',
    salary: "Not specific",
    deadline: "Not specific",
},
{
    id: "Project / Field Engineer",
    title: "Project / Field Engineer",
    location: "Port Harcourt, Rivers",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We are seeking a highly qualified Project Engineer to join our team. As a Project / Field Engineer, you will play a crucial role in overseeing the technical and practical execution of engineering projects offsite and on-site. You will also be responsible for ensuring projects are completed safely, on time, within budget, and according to design specifications.",
    responsibilities: [
      "Prepare, schedule, coordinate and monitor the assigned engineering projects",
"Responsible for scheduling, conducting and coordinating the technical and managerial aspect of projects.",
"Monitoring project status reports and change orders.",
"Accountable for the successful completion of engineering projects.",
"Requires extensive regular contact with assigned project clients.",
"Assist in the preparation of engineering projects proposals.",
"Budget monitoring and trend tracking.",
"Participate in Client / Contractor meetings and resolving Client / Engineering and management project issues.",
"Keep an eye on all relevant safety objectives and legal requirements.",
"Interpret clients requirements.",
"Identify engineering problems and ensure solutions are implemented.",
"Evaluate, organize and prioritize workload within a schedule.",
"Liaise with third party contractors to ensure all equipment are fit for purpose.",
"Take responsibility for a team of engineers.",
"Take full responsibility for any assigned project from commencement to completion whether on shoe, offshore or swamp.",
    ],
    requirements: [
      "B.Sc. / B.Eng. / HND in engineering field. A Masters’ degree will be an added advantage with Experience: 3–5 years post qualification / (NYSC) experience, COREN / NSE membership is an added advantage",
"Proven experience working in a Project management role in manufacturing, construction and / or oil and gas industries",
"Verifiable experience in the use of MS Office packages.",
"HSE Level 3 minimum",
"Should reside in Port Harcourt or willing to relocate.",
"Should have skills like,: Microsoft Office Project, Primavera, Ability to use initiative, The ability to explain design and plans clearly and Confident decision-making ability",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:offixrecruit@gmail.com ">offixrecruit@gmail.com </a> using “Project / Field Engineer” title as the subject of the mail.',
    salary: "Not specific",
    deadline: "28th march, 2026",
},
    {
    id: "Medical Laboratory Scientist",
    title: "Medical Laboratory Scientist",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We are looking for a professional who is passionate about precision in laboratory testing, quality assurance, and contributing to high-standard healthcare delivery . We are seeking a competent, detail-oriented, and experienced Medical Laboratory Scientist to strengthen our diagnostics team. We are dedicated to providing accurate, reliable, and timely laboratory results that directly support clinical diagnosis, treatment decisions, and patient care excellence.",
    responsibilities: [
      "Conduct a comprehensive range of laboratory investigations in hematology, clinical chemistry, microbiology, parasitology, immunology, serology, coagulation, and urinalysis.",
"Receive, process, and analyze various clinical specimens (blood, urine, body fluids, swabs, tissues, etc.) using both manual and automated techniques.",
"Operate, calibrate, maintain, and perform daily/periodic quality control on laboratory analyzers and equipment.",
"Interpret test results, verify abnormal findings, and escalate critical values to clinicians in a timely manner.",
"Ensure strict compliance with infection prevention and control protocols, biohazard waste management, and laboratory safety standards.",
"Maintain accurate, complete, and confidential records of all tests, results, and procedures in the laboratory information system (LIS).",
"Assist in reagent preparation, inventory management, stock monitoring, and ordering of laboratory consumables.",
"Support continuous improvement initiatives, equipment troubleshooting, and training of junior staff or interns where applicable.",
"Collaborate with pathologists, clinicians, and other healthcare professionals to ensure diagnostic accuracy and optimal patient outcomes.",
    ],
    requirements: [
      "Bachelor of Medical Laboratory Science (BMLS) Degree from a recognized and accredited institution..",
"Full registration and valid/current practicing license from the Medical Laboratory Science Council of Nigeria (MLSCN)..",
"2–4 years of post-qualification experience in a busy hospital laboratory, diagnostic center, or private pathology lab..",
"Hands-on experience with automated analyzers (hematology, chemistry, immunoassay), microbiology culture techniques, and blood banking procedures is highly desirable..",
"Strong technical proficiency across multiple laboratory disciplines with excellent hands-on skills.",
"Ability to work efficiently in a high-volume environment while maintaining accuracy under pressure.",
"Strong organizational skills and commitment to documentation, traceability, and result integrity.",
"Effective communication skills for clear reporting of results and professional interaction with clinical teams.",
"Dedication to ethical practice, patient confidentiality, safety, and lifelong learning.",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:Admin@clinixhealthcare.com.ng">Admin@clinixhealthcare.com.ng</a> and copy to: <a href="mailto:hr@clinixhealthcare.com.ng"> hr@clinixhealthcare.com.ng</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "Not specific",
},
{
    id: "Field Operator III",
    title: "Field Operator III",
    location: "EDOP Platform, Akwa Ibom",
    type: "Contract",
    seniority: "Junior",
    summary:
      "Operate equipment and wells by applying operating and safety procedures and guidelines to meet daily operational plan, reduce equipment failure and efficient resources administration.",
    responsibilities: [
      "Responsible to implement on daily work objectives, housekeeping, safety, health, environmental and security",
"Active participation on daily toolbox meetings and regular, reported safety meetings",
"Identify and implement corrective and optimization actions by the continuous surveillance of wells and equipment to ensure reliable, efficient and safe operational conditions",
"Function as Equipment Care Technician, and routinely use Maintenance skills in performing simple maintenance activities",
"Report when the alarm, emergency or emergency shutdown system is out of service",
"Provide detailed, clear and accurate information when changing shift, to guarantee that unit conditions are updated and ensure operations continuity",
"Coordinate, control and monitor maintenance jobs according with the corrective, predictive and preventive planning",
"Report continuously in the log book all relevant operational events and abnormal situations or deviation occurred in the work area, equipment or personnel",
"Take samples of products for laboratory analysis and execute field laboratory tests",
"Active participation on emergency response activities",
"Report incidents internally and escalate awareness as per the Incident Reporting Guidelines",
"Ensure that Operations Shift Supervisor is informed and consulted about operations activities",
"Ensure good communication across the work team so that issues / actions can be adequately addressed",
"Provide the basic facts concerning well producing problems, current production rates, and current condition of the well",
"Ensure that the well problem diagnostics are thorough and complete before requesting Well Work intervention operations",
    ],
    requirements: [
      "Completed secondary education and worked previously as a Field Technician",
      "High standard of safety, Health, Environment apttitude and cultivates the same in others",
      "Extensive knowledge and/or experience of pipeline operations",
	"Entensive knowledge of Project Phylosophy and Design Specifications.",
	"Strong communication (oral and written)",
    ],
    apply:
      'Interested and qualified candidates should send their CV in MS Word to: <a href="mailto:job@abnl.net">job@abnl.net</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "16th March, 2026",
},
{
    id: "Product Marketing Manager",
    title: "Product Marketing Manager",
    location: "Lagos",
    type: "Remote",
    seniority: "Senior",
    summary:
      "The Naval Architect is responsible for the design, development, and optimization of marine vessels and offshore structures.",
    responsibilities: [
      "You’ll own the GTM strategy for key products, shaping messaging and positioning that speaks to developers and enterprise buyers alike.",
"You’ll collaborate cross-functionally with product management, sales, regional marketing, content, and partner marketing teams to bring campaigns to life.",
"You’ll get creative, crafting compelling advertising, launch plans, and campaigns that make our products stand out in a competitive landscape.",
"You’ll measure impact, using data to refine messaging, optimize marketing funnels, and drive customer engagement.",
"You’ll be part of a truly global team, working with colleagues in over 85 countries in a fully remote, high-performance environment.",
"Develop and execute go-to-market (GTM) strategies for a range of products.",
"Lead messaging and positioning efforts ensuring our products stand out in a competitive market.",
"Lead content planning with product managers —from website copy to whitepapers, blogs, and sales enablement materials.",
"Collaborate on marketing campaigns, partnering with regional marketing teams to execute integrated campaigns that drive pipeline growth.",
"Launch new products and features, leading cross-functional teams to drive awareness and adoption.",
"Run competitive analysis, staying ahead of market trends and evolving our positioning accordingly.",
"Support the customer success team on driving customer engagement and growth, working on strategies to upsell and cross-sell across our customer base.",
"Plan and execute global events, live webinars, and community meetups that align with our GTM priorities.",
    ],
    requirements: [
      "A passion for technology and open source—you get excited about innovation, software, and community-driven development.",
"Strong storytelling skills—you know how to craft messaging that resonates with both technical and business audiences.",
"Growth mindset—someone who thrives on experimentation, learning, and continuous improvement.",
"Excellent communication skills, both written and verbal.",
"Data-driven mindset, using insights to refine strategies and improve performance.",
"Experience in product marketing for enterprise software, cloud, DevOps, or open-source solutions.",
"Experience with demand generation, understanding how to translate GTM strategies into pipeline growth.",
"Comfort working cross-functionally with product, sales, partners, and marketing teams.",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="https://job-boards.greenhouse.io/canonicaljobs/jobs/7619278?gh_src=jpx8xfro1us">HERE</a> to apply online.',
    salary: "Your base pay will depend on various factors including your geographical location, level of experience, knowledge and skills. Please note that additional benefits may apply depending on the work location and, for more information on these, please ask your Talent Partner.",
    deadline: "Not specific",
},
{
    id: "Assistant QHSE Manager",
    title: "Assistant QHSE Manager",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "A Marine Logistics provider is seeking a highly motivated and experienced Assistant QHSE Manager to champion and drive continual improvement in operational safety management across our marine fleet and onshore operations. The Ideal candidate will be responsible for implementing the company’s  HSE plan, leading compliance initiatives, and ensuring a safe, efficient, and legally compliant working environment in alignment with international and company standards. The position is primarily based in Lagos.",
    responsibilities: [
      "Drive continual, measurable, and sustainable improvement in HSE performance in line with  strategic objectives.",
"Investigate incidents thoroughly, identify root causes, and implement corrective actions to prevent recurrence.",
"Maintain and monitor the Offshore Vessel Management Self-Assessment (OVMSA) system, ensuring full compliance with IOGP standards.",
"Monitor and close out OVID inspection non-conformances across vessels.",
"Develop and implement the yearly QHSE plan for marine and onshore operations.",
"Collect, analyze, and report HSE statistics, identifying trends and developing proactive measures to minimize incidents.",
"Conduct annual reviews of the Safety Management System to ensure alignment with international best practices.",
"Lead HSE campaigns and trainings across the organization, both offshore and onshore.",
"Establish and monitor emergency preparedness plans through drills and training programs.",
    ],
    requirements: [
      "Bachelor’s Degree or equivalent from a reputable institution with inimum of 5 years’ work experience in the oil and gas industry, with at least 2 years in a similar HSE function.",
"NEBOSH IGC or Diploma (preferred).",
"Master’s degree in a relevant field (an added advantage).",
"Strong knowledge of HSE regulations and best practices in the oil and gas/marine sector.",
"Excellent analytical, incident investigation, and reporting skills.",
"Effective communication and leadership abilities.",
"Ability to manage and implement structured safety programs across multi-site operations.",
    ],
    apply:
      'Interested and qualified candidates should click: <a href="">HERE</a> to apply.',
    salary: "Not specific",
    deadline: "2Oth March, 2026",
    },
    {
    id: "Surveyor",
    title: "Surveyor",
    location: "Ode-Remo – Abeokuta, Ogun",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "We are seeking a skilled and experienced Surveyor with a minimum of 6 years of professional experience in land surveying. The ideal candidate must be familiar with the Lands Department in Abeokuta and understand the processes involved in land documentation, approvals, and boundary verification. The Surveyor will be responsible for conducting land measurements, preparing survey plans, and ensuring compliance with regulatory requirements.",
    responsibilities: [
      "Carry out land and property surveys for acquisition, development, and documentation.",
"Prepare survey plans, maps, and technical reports for land registration and approvals.",
"Liaise with the Lands Department in Abeokuta for survey plan submissions, charting, and other regulatory processes.",
"Conduct site inspections and boundary verification to ensure accurate land measurements.",
"Operate and maintain survey equipment such as Total Station, GPS, and other surveying tools.",
"Assist in land documentation and title processing where required.",
"Work closely with engineers, architects, and project teams to provide accurate survey data",
"Maintain proper survey records and documentation for company projects.",
"Ensure all survey activities comply with government regulations and professional standards.",
    ],
    requirements: [
      "HND or Bachelor’s Degree in Surveying, Geomatics, or a related field with a minimum of 6 years of proven experience in land surveying.",
"Must be familiar with the Lands Department procedures in Abeokuta.",
"Strong knowledge of survey equipment such as GPS, Total Station, and mapping software.",
"Good understanding of land documentation and boundary identification.",
"Excellent communication and teamwork skills.",
"Ability to work independently and handle multiple projects effectively.",
"Skills needed are: Land Surveying and Mapping, Boundary Identification, Survey Equipment Operation, Land Documentation Processes, Data Analysis and Reporting and Team Collaboration",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:ninestars.recruitment@yahoo.com">ninestars.recruitment@yahoo.com</a> using “Surveyor Application”  as the subject of the mail.',
    salary: "N300,000 – N400,000 / month",
    deadline: "31st March, 2026",
    },
    {
    id: "Naval-Architect",
    title: "Naval Architect",
    location: "Lagos",
    type: "Full-time",
    seniority: "Senior",
    summary:
      "The Naval Architect is responsible for the design, development, and optimization of marine vessels and offshore structures.",
    responsibilities: [
      "Design end-to-end user experiences",
      "Mentor junior designers",
      "Collaborate with PMs and engineers",
    ],
    requirements: [
      "BEng / BTech in Naval Architecture, Marine Engineering, or Ocean Engineering",
      "Minimum 5+ years’ experience in vessel design, structural analysis, or shipbuilding projects",
      "Proficiency in marine design and analysis software (AutoCAD, Rhino, Maxsurf, ANSYS, or equivalent)",
    ],
    apply:
      'Interested and qualified candidates should send their CV to: <a href="mailto:hr@russelsmithgroup.com">hr@russelsmithgroup.com</a> using the job title as the subject of the mail.',
    salary: "Not specific",
    deadline: "Not specific",
  },
];
